# Generated by Django 3.0.8 on 2020-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WemoSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(max_length=255)),
                ('desired_state', models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('scheduled', 'Scheduled')], default='off', max_length=255)),
            ],
        ),
    ]
