# Generated by Django 3.0.8 on 2020-07-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='I2CMonitorAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_state', models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('scheduled', 'Scheduled')], default='off', max_length=255)),
                ('failed_threshold', models.FloatField()),
                ('recovered_state', models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('scheduled', 'Scheduled')], default='on', max_length=255)),
                ('recovered_threshold', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.I2CJob')),
                ('high_low_threshold', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=255)),
                ('power_switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.WemoSwitch'))
            ],
        ),
    ]
